In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [3]:
fingerprint_list = ['MorganFP', 'RDkitFP', 'AtomPairFP', 'TorsionFP', 'AvalonFP', 
'EstateFP', 'MACCSFP', 'PharmacoErGFP', 'PharmacoPFP', 'PubChemFP', 'MHFP6', 'MAP4']
descriptor_list = ['Property', 'Constitution', 'Autocorr', 'Fragment', 'Charge', 
'Estate', 'MOE', 'Connectivity', 'Topology', 'Kappa', 'Path', 'Matrix', 'InfoContent']

In [4]:
df=pd.DataFrame()

In [5]:
for fp in descriptor_list:
    fp_file=f'ChblReg6227_{fp}.csv';#print(fp_file)
    tdf=pd.read_csv(fp_file)
    df=pd.concat([df,tdf],axis=1)

In [6]:
print(len(df));print(len(df.columns))

6227
1456


In [7]:
df.to_csv('all_desc.csv',index=False)

# remove those columns with same values

In [8]:
nunique = df.nunique()
cols_to_drop = nunique[nunique == 1].index
print(f'cols_to_drop = {cols_to_drop}')

cols_to_drop = Index(['NumRadicalElectrons', 'NumCyclicTripleBonds', 'fr_nitroso', 'fr_diazo',
       'fr_isocyan', 'fr_thiocyan', 'fr_SH', 'fr_prisulfonamd', 'fr_barbitur',
       'fr_dihydropyridine',
       ...
       'SpMAD_Dt', 'LogEE_Dt', 'SM1_Dt', 'VE1_Dt', 'VE2_Dt', 'VE3_Dt',
       'VR1_Dt', 'VR2_Dt', 'VR3_Dt', 'DetourIndex'],
      dtype='object', length=201)


In [9]:
pd.DataFrame(cols_to_drop.to_list()).to_csv('desc_cols_to_drop.csv')

In [10]:
df.drop(cols_to_drop, axis=1,inplace=True)

In [11]:
df.to_csv('all_desc_drop_same_value_cols.csv')

In [12]:
T=df.T

In [13]:
len(T)

1255

In [14]:
T.drop_duplicates(inplace=True)

In [15]:
len(T)

1207

In [16]:
df=T.T

In [18]:
df.head(5)

MolWeight  MolExactWeight  MolAverageWeight  MolHeavyAtomWeight  \
0     409.50          409.25         13.648438              382.25   
1     319.25          319.25         13.882812              298.25   
2     426.50          426.25         13.757812              399.25   
3     367.50          367.25         13.609375              346.25   
4     440.50          440.25         13.765625              411.25   

   MolFilterItLogS  MolSLogP  MolQedWeightsMax  MolQedWeightsMean  \
0        -7.292969  3.472656          0.510254           0.500488   
1        -4.921875  2.761719          0.558594           0.631348   
2        -7.925781  4.218750          0.486328           0.475830   
3        -6.113281  2.302734          0.698242           0.668457   
4        -7.476562  4.226562          0.490479           0.479248   

   MolQedWeightsNone  MolRefractivity  ...      MIC2      MIC3      MIC4  \
0           0.542480         116.4375  ...  40.59375  41.53125  41.53125   
1           0.718262          87.3750  ...  38.15625  38.96875  39.12500   
2           0.540039         118.5625  ...  41.65625  42.68750  42.68750   
3           0.664062         102.5625  ...  41.50000  42.43750  42.43750   
4           0.548828         123.1875  ...  41.37500  42.40625  42.40625   

       MIC5     ZMIC0     ZMIC1      ZMIC2      ZMIC3      ZMIC4      ZMIC5  
0  41.53125  100.0000  44.87500  26.984375  23.843750  23.843750  23.843750  
1  39.12500   79.8750  36.96875  25.984375  23.750000  22.984375  22.984375  
2  42.68750  101.5000  50.34375  28.312500  24.343750  24.343750  24.343750  
3  42.43750   88.9375  41.12500  26.140625  23.828125  23.828125  23.828125  
4  42.40625  105.3125  51.09375  28.437500  24.578125  24.578125  24.578125  

[5 rows x 1207 columns]

In [19]:
df.to_csv('all_desc_dropSame_DeDup.csv',index=False)

In [24]:
np.max(df.values,axis=0)

array([1211.   , 1209.   ,   21.25 , ...,  125.125,  117.75 ,  110.375])

In [23]:
df.values

array([[409.5      , 409.25     ,  13.6484375, ...,  23.84375  ,
         23.84375  ,  23.84375  ],
       [319.25     , 319.25     ,  13.8828125, ...,  23.75     ,
         22.984375 ,  22.984375 ],
       [426.5      , 426.25     ,  13.7578125, ...,  24.34375  ,
         24.34375  ,  24.34375  ],
       ...,
       [399.5      , 399.25     ,  14.265625 , ...,  34.21875  ,
         34.21875  ,  34.21875  ],
       [418.75     , 418.25     ,  14.9609375, ...,  36.03125  ,
         36.03125  ,  36.03125  ],
       [297.5      , 297.25     ,  14.1640625, ...,  27.578125 ,
         27.578125 ,  27.578125 ]])

In [28]:
max(np.max(df.values,axis=0))

inf

In [39]:
cols=df.columns
#for c in cols: df.isna()

In [48]:
for c in cols:
    if (df[cols[0]].isna()).all():
        print(df[df[cols[0]].isna()])

In [56]:
np.where(df.values==np.inf)

(array([ 543,  786, 1158, 1177, 1304, 1649, 1704, 1817, 1838, 1968, 2073,
        2074, 2076, 2150, 2171, 2229, 2238, 2238, 2289, 2289, 2292, 2333,
        2384, 2384, 2388, 2438, 2438, 2445, 2445, 2470, 2470, 2539, 2588,
        2613, 2626, 2664, 2715, 2726, 2821, 2822, 2830, 2830, 2872, 2885,
        2916, 2941, 3002, 3034, 3067, 3151, 3284, 3285, 3288, 3294, 3301,
        3305, 3311, 3345, 3348, 3466, 3466, 3530, 3534, 5927, 5927, 5927,
        5927, 5927, 5927, 5927, 5927, 5927, 6139, 6139, 6147, 6147, 6147,
        6147, 6147, 6147, 6147, 6147, 6147, 6147, 6147, 6147, 6157, 6194,
        6194, 6194, 6194, 6194, 6194, 6194, 6194, 6194, 6194, 6194, 6194,
        6194, 6196], dtype=int64),
 array([1056, 1056, 1056, 1056, 1056, 1056, 1056, 1056, 1056, 1056, 1056,
        1056, 1056, 1056, 1056, 1056, 1056, 1057, 1056, 1057, 1056, 1056,
        1056, 1057, 1056, 1056, 1057, 1056, 1057, 1056, 1057, 1056, 1056,
        1056, 1056, 1056, 1056, 1056, 1056, 1056, 1056, 1057, 1056, 1056,
   

In [59]:
df.iloc[np.where(df.values==np.inf)[0],np.where(df.values==np.inf)[1]]

VR1_A    VR1_A    VR1_A    VR1_A    VR1_A    VR1_A    VR1_A    VR1_A  \
543       inf      inf      inf      inf      inf      inf      inf      inf   
786       inf      inf      inf      inf      inf      inf      inf      inf   
1158      inf      inf      inf      inf      inf      inf      inf      inf   
1177      inf      inf      inf      inf      inf      inf      inf      inf   
1304      inf      inf      inf      inf      inf      inf      inf      inf   
1649      inf      inf      inf      inf      inf      inf      inf      inf   
1704      inf      inf      inf      inf      inf      inf      inf      inf   
1817      inf      inf      inf      inf      inf      inf      inf      inf   
1838      inf      inf      inf      inf      inf      inf      inf      inf   
1968      inf      inf      inf      inf      inf      inf      inf      inf   
2073      inf      inf      inf      inf      inf      inf      inf      inf   
2074      inf      inf      inf      inf      inf      inf      inf      inf   
2076      inf      inf      inf      inf      inf      inf      inf      inf   
2150      inf      inf      inf      inf      inf      inf      inf      inf   
2171      inf      inf      inf      inf      inf      inf      inf      inf   
2229      inf      inf      inf      inf      inf      inf      inf      inf   
2238      inf      inf      inf      inf      inf      inf      inf      inf   
2238      inf      inf      inf      inf      inf      inf      inf      inf   
2289      inf      inf      inf      inf      inf      inf      inf      inf   
2289      inf      inf      inf      inf      inf      inf      inf      inf   
2292      inf      inf      inf      inf      inf      inf      inf      inf   
2333      inf      inf      inf      inf      inf      inf      inf      inf   
2384      inf      inf      inf      inf      inf      inf      inf      inf   
2384      inf      inf      inf      inf      inf      inf      inf      inf   
2388      inf      inf      inf      inf      inf      inf      inf      inf   
2438      inf      inf      inf      inf      inf      inf      inf      inf   
2438      inf      inf      inf      inf      inf      inf      inf      inf   
2445      inf      inf      inf      inf      inf      inf      inf      inf   
2445      inf      inf      inf      inf      inf      inf      inf      inf   
2470      inf      inf      inf      inf      inf      inf      inf      inf   
...       ...      ...      ...      ...      ...      ...      ...      ...   
5927      inf      inf      inf      inf      inf      inf      inf      inf   
6139      inf      inf      inf      inf      inf      inf      inf      inf   
6139      inf      inf      inf      inf      inf      inf      inf      inf   
6147  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0   
6147  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0   
6147  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0   
6147  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0   
6147  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0   
6147  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0   
6147  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0   
6147  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0   
6147  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0   
6147  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0   
6147  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0   
6147  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0  20016.0   
6157      inf      inf      inf      inf      inf      inf      inf      inf   
6194      inf      inf      inf      inf      inf      inf      inf      inf   
6194      inf      inf      inf      inf      inf      inf      inf      inf   
6194    

In [55]:
df.iloc[:,~]

array([ 543,  786, 1158, 1177, 1304, 1649, 1704, 1817, 1838, 1968, 2073,
       2074, 2076, 2150, 2171, 2229, 2238, 2238, 2289, 2289, 2292, 2333,
       2384, 2384, 2388, 2438, 2438, 2445, 2445, 2470, 2470, 2539, 2588,
       2613, 2626, 2664, 2715, 2726, 2821, 2822, 2830, 2830, 2872, 2885,
       2916, 2941, 3002, 3034, 3067, 3151, 3284, 3285, 3288, 3294, 3301,
       3305, 3311, 3345, 3348, 3466, 3466, 3530, 3534, 5927, 5927, 5927,
       5927, 5927, 5927, 5927, 5927, 5927, 6139, 6139, 6147, 6147, 6147,
       6147, 6147, 6147, 6147, 6147, 6147, 6147, 6147, 6147, 6157, 6194,
       6194, 6194, 6194, 6194, 6194, 6194, 6194, 6194, 6194, 6194, 6194,
       6194, 6196], dtype=int64)

In [67]:
np.where(df.values==np.inf)[1]

array([1056, 1056, 1056, 1056, 1056, 1056, 1056, 1056, 1056, 1056, 1056,
       1056, 1056, 1056, 1056, 1056, 1056, 1057, 1056, 1057, 1056, 1056,
       1056, 1057, 1056, 1056, 1057, 1056, 1057, 1056, 1057, 1056, 1056,
       1056, 1056, 1056, 1056, 1056, 1056, 1056, 1056, 1057, 1056, 1056,
       1056, 1056, 1056, 1056, 1056, 1056, 1056, 1056, 1056, 1056, 1056,
       1056, 1056, 1056, 1056,  174,  177, 1056, 1056,  129,  130,  131,
        132,  174,  175,  177, 1056, 1057, 1056, 1057,  127,  128,  129,
        130,  131,  132,  172,  173,  174,  175,  176,  177, 1056,  127,
        128,  129,  130,  131,  132,  172,  173,  174,  175,  176,  177,
       1056, 1056], dtype=int64)

In [68]:
inf_cols_num=np.where(df.values==np.inf)[1]
173 in inf_cols_num

True

In [70]:
no_inf_cols_num=[n for n in range(len(df.columns)) if n not in inf_cols_num]

In [71]:
no_inf_df=df.iloc[:,no_inf_cols_num]

In [72]:
no_inf_df.to_csv('all_desc_dropSame_DeDup_rmInf.csv')

In [79]:
scaler=MinMaxScaler()
scaler.fit(no_inf_df.values)

MinMaxScaler()

In [81]:
trans_val=scaler.transform(no_inf_df.values)

In [82]:
trans_df=pd.DataFrame(trans_val,columns=no_inf_df.columns)

In [83]:
trans_df

MolWeight  MolExactWeight  MolAverageWeight  MolHeavyAtomWeight  \
0      0.214697        0.215066          0.080340            0.221461   
1      0.126271        0.126733          0.108696            0.134583   
2      0.231353        0.231751          0.093573            0.239043   
3      0.173546        0.173844          0.075614            0.184228   
4      0.245070        0.245491          0.094518            0.251454   
5      0.203919        0.204269          0.091682            0.214221   
6      0.286222        0.286713          0.097353            0.288688   
7      0.176485        0.176788          0.089792            0.169748   
8      0.098836        0.099006          0.107750            0.109761   
9      0.176485        0.176788          0.089792            0.169748   
10     0.231353        0.231751          0.093573            0.239043   
11     0.245805        0.245246          0.208885            0.259729   
12     0.245070        0.245491          0.094518            0.251454   
13     0.201960        0.202306          0.083176            0.215255   
14     0.236252        0.236658          0.113422            0.238009   
15     0.157869        0.158140          0.129490            0.164577   
16     0.244091        0.244510          0.090737            0.254557   
17     0.174525        0.174825          0.080340            0.178022   
18     0.186283        0.186603          0.072779            0.194570   
19     0.306062        0.306343          0.118147            0.306529   
20     0.292345        0.292602          0.118147            0.294118   
21     0.200000        0.200344          0.075614            0.198707   
22     0.229394        0.229788          0.086011            0.227666   
23     0.276179        0.275672          0.333648            0.290756   
24     0.175505        0.175807          0.085066            0.175953   
25     0.132394        0.132622          0.069943            0.134583   
26     0.159829        0.160103          0.073724            0.159405   
27     0.213717        0.214084          0.076560            0.215255   
28     0.192162        0.192492          0.099244            0.186296   
29     0.192162        0.192492          0.099244            0.186296   
...         ...             ...               ...                 ...   
6197   0.331292        0.329653          0.559546            0.350743   
6198   0.252909        0.252362          0.366730            0.258694   
6199   0.260012        0.258987          0.398866            0.279897   
6200   0.153705        0.154214          0.110586            0.165611   
6201   0.241396        0.241320          0.190926            0.261280   
6202   0.287446        0.286468          0.379962            0.304719   
6203   0.177465        0.177770          0.093573            0.180090   
6204   0.269565        0.270028          0.086011            0.275242   
6205   0.363625        0.363023          0.771267            0.386684   
6206   0.267851        0.266838          0.299622            0.284034   
6207   0.337661        0.337995          0.087902            0.327214   
6208   0.204899        0.205251          0.095463            0.204913   
6209   0.638457        0.639308          0.072779            0.627149   
6210   0.122596        0.122807          0.087902            0.126309   
6211   0.168157        0.167955          0.180529            0.171299   
6212   0.193141        0.193473          0.103970            0.188365   
6213   0.124556        0.124770          0.098299            0.130446   
6214   0.154440        0.154214          0.182420            0.158888   
6215   0.151990        0.152251          0.101134            0.155268   
6216   0.168157        0.167955          0.180529            0.171299   
6217   0.177465        0.177770          0.094518            0.171816   
6218   0.189222        0.189547          0.147448            0.197673   
6219   0.171586        0.171881          0.129490            0.1

In [84]:
trans_df.to_csv('MinMaxed_desc.csv',index=False)

In [85]:
df=pd.DataFrame()
for fp in fingerprint_list:
    fp_file=f'ChblReg6227_{fp}.csv';#print(fp_file)
    tdf=pd.read_csv(fp_file)
    df=pd.concat([df,tdf],axis=1)

In [86]:
df.head(5)

MorganFP0  MorganFP1  MorganFP2  MorganFP3  MorganFP4  MorganFP5  \
0          0          0          0          0          0          0   
1          0          0          0          0          0          0   
2          0          0          0          0          0          0   
3          0          0          0          0          0          0   
4          0          0          0          0          0          0   

   MorganFP6  MorganFP7  MorganFP8  MorganFP9  ...  MAP42038  MAP42039  \
0          0          0          1          0  ...         0         1   
1          0          0          0          0  ...         0         0   
2          0          0          1          0  ...         0         1   
3          0          0          1          0  ...         0         1   
4          0          0          1          0  ...         0         1   

   MAP42040  MAP42041  MAP42042  MAP42043  MAP42044  MAP42045  MAP42046  \
0         0         1         0         0         0         0         0   
1         0         0         1         0         0         0         0   
2         0         1         0         0         0         0         1   
3         0         1         0         0         0         0         0   
4         0         1         0         0         0         1         1   

   MAP42047  
0         0  
1         0  
2         0  
3         0  
4         0  

[5 rows x 16204 columns]

In [87]:
print(len(df));print(len(df.columns))

6227
16204


In [88]:
df.to_csv('all_fp.csv',index=False)

In [89]:
nunique = df.nunique()
cols_to_drop = nunique[nunique == 1].index
print(f'cols_to_drop = {cols_to_drop}')
pd.DataFrame(cols_to_drop.to_list()).to_csv('fp_cols_to_drop.csv')

cols_to_drop = Index(['MorganFP51', 'MorganFP438', 'MorganFP979', 'MorganFP1591',
       'AtomPairFP3', 'AtomPairFP8', 'AtomPairFP16', 'AtomPairFP51',
       'AtomPairFP57', 'AtomPairFP64',
       ...
       'PubChemFP871', 'PubChemFP872', 'PubChemFP873', 'PubChemFP874',
       'PubChemFP875', 'PubChemFP876', 'PubChemFP877', 'PubChemFP878',
       'PubChemFP879', 'PubChemFP880'],
      dtype='object', length=1158)


In [90]:
df.drop(cols_to_drop, axis=1,inplace=True)
df.to_csv('all_fp_dropSame.csv')

In [91]:
print(len(df));print(len(df.columns))

6227
15046


In [92]:
T=df.T
T.drop_duplicates(inplace=True)

In [93]:
print(len(T));print(len(T.columns))

14770
6227


In [94]:
df=T.T

In [95]:
print(len(df));print(len(df.columns))

6227
14770


In [96]:
df.head(5)

MorganFP0  MorganFP1  MorganFP2  MorganFP3  MorganFP4  MorganFP5  \
0          0          0          0          0          0          0   
1          0          0          0          0          0          0   
2          0          0          0          0          0          0   
3          0          0          0          0          0          0   
4          0          0          0          0          0          0   

   MorganFP6  MorganFP7  MorganFP8  MorganFP9  ...  MAP42038  MAP42039  \
0          0          0          1          0  ...         0         1   
1          0          0          0          0  ...         0         0   
2          0          0          1          0  ...         0         1   
3          0          0          1          0  ...         0         1   
4          0          0          1          0  ...         0         1   

   MAP42040  MAP42041  MAP42042  MAP42043  MAP42044  MAP42045  MAP42046  \
0         0         1         0         0         0         0         0   
1         0         0         1         0         0         0         0   
2         0         1         0         0         0         0         1   
3         0         1         0         0         0         0         0   
4         0         1         0         0         0         1         1   

   MAP42047  
0         0  
1         0  
2         0  
3         0  
4         0  

[5 rows x 14770 columns]

In [97]:
df.to_csv('all_fp_dropSame_DeDup.csv',index=False)

In [98]:
df

MorganFP0  MorganFP1  MorganFP2  MorganFP3  MorganFP4  MorganFP5  \
0             0          0          0          0          0          0   
1             0          0          0          0          0          0   
2             0          0          0          0          0          0   
3             0          0          0          0          0          0   
4             0          0          0          0          0          0   
5             0          0          0          0          0          0   
6             0          0          0          0          0          0   
7             0          0          0          0          0          0   
8             0          0          0          0          0          0   
9             0          0          0          0          0          0   
10            0          0          0          0          0          0   
11            0          0          1          0          0          0   
12            0          0          0          0          0          0   
13            0          0          0          0          0          0   
14            0          0          0          0          0          0   
15            0          0          0          0          0          0   
16            0          0          0          0          0          0   
17            0          0          0          0          0          0   
18            0          0          0          0          0          0   
19            0          0          0          0          0          0   
20            0          0          0          0          0          0   
21            0          0          1          0          0          0   
22            0          0          0          0          0          0   
23            0          0          0          0          0          0   
24            0          0          0          0          0          0   
25            0          0          0          0          0          0   
26            0          0          0          0          0          0   
27            0          0          0          0          0          0   
28            0          0          0          0          0          0   
29            0          0          0          0          0          0   
...         ...        ...        ...        ...        ...        ...   
6197          0          0          1          0          0          0   
6198          0          0          0          0          0          0   
6199          0          0          0          0          0          0   
6200          0          0          0          0          0          0   
6201          0          0          0          0          0          0   
6202          0          0          1          0          0          0   
6203          0          0          0          0          0          0   
6204          0          0          0          0          0          0   
6205          0          0          1          0          0          0   
6206          0          0          1          0          0          0   
6207          0          0          0          0          0          0   
6208          0          0          1          0          0          0   
6209          0          0          0          0          0          0   
6210          0          0          0          0          0          0   
6211          0          0          0          0          0          0   
6212          0          0          0          0          0          0   
6213          0          0          0          0          0          0   
6214          0          0          0          0          0          0   
6215          0          0          0          0          0          0   
6216          0          0          0          0          0          0   
6217          0          0          0          0          0          0   
6218          0          0          0          0          0          0   
6219      

In [99]:
no_inf_df

MolWeight  MolExactWeight  MolAverageWeight  MolHeavyAtomWeight  \
0        409.50          409.25         13.648438              382.25   
1        319.25          319.25         13.882812              298.25   
2        426.50          426.25         13.757812              399.25   
3        367.50          367.25         13.609375              346.25   
4        440.50          440.25         13.765625              411.25   
5        398.50          398.25         13.742188              375.25   
6        482.50          482.25         13.789062              447.25   
7        370.50          370.25         13.726562              332.25   
8        291.25          291.00         13.875000              274.25   
9        370.50          370.25         13.726562              332.25   
10       426.50          426.25         13.757812              399.25   
11       441.25          440.00         14.710938              419.25   
12       440.50          440.25         13.765625              411.25   
13       396.50          396.25         13.671875              376.25   
14       431.50          431.25         13.921875              398.25   
15       351.50          351.25         14.054688              327.25   
16       439.50          439.25         13.734375              414.25   
17       368.50          368.25         13.648438              340.25   
18       380.50          380.25         13.585938              356.25   
19       502.75          502.25         13.960938              464.50   
20       488.75          488.25         13.960938              452.50   
21       394.50          394.25         13.609375              360.25   
22       424.50          424.25         13.695312              388.25   
23       472.25          471.00         15.742188              449.25   
24       369.50          369.25         13.687500              338.25   
25       325.50          325.25         13.562500              298.25   
26       353.50          353.25         13.593750              322.25   
27       408.50          408.25         13.617188              376.25   
28       386.50          386.25         13.804688              348.25   
29       386.50          386.25         13.804688              348.25   
...         ...             ...               ...                 ...   
6197     528.50          526.00         17.609375              507.25   
6198     448.50          447.25         16.015625              418.25   
6199     455.75          454.00         16.281250              438.75   
6200     347.25          347.25         13.898438              328.25   
6201     436.75          436.00         14.562500              420.75   
6202     483.75          482.00         16.125000              462.75   
6203     371.50          371.25         13.757812              342.25   
6204     465.50          465.25         13.695312              434.25   
6205     561.50          560.00         19.359375              542.00   
6206     463.75          462.00         15.460938              442.75   
6207     535.00          534.50         13.710938              484.50   
6208     399.50          399.25         13.773438              366.25   
6209     842.00          841.50         13.585938              774.50   
6210     315.50          315.25         13.710938              290.25   
6211     362.00          361.25         14.476562              333.75   
6212     387.50          387.25         13.843750              350.25   
6213     317.50          317.25         13.796875              294.25   
6214     348.00          347.25         14.492188              321.75   
6215     345.50          345.25         13.820312              318.25   
6216     362.00          361.25         14.476562              333.75   
6217     371.50          371.25         13.765625              334.25   
6218     383.50          383.25         14.203125              359.25   
6219     365.50          365.25         14.054688              3

In [100]:
desc_fp_df=pd.concat([no_inf_df,df],axis=1)

In [101]:
desc_fp_df.to_csv('desc_fp_precocessed.csv',index=False)